/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gnu.glpk;


/**
 * Wrapper class for pointer generated by SWIG.
 * <p>Please, refer to doc/glpk-java.pdf of the GLPK for Java distribution
 * and to doc/glpk.pdf of the GLPK source distribution
 * for details. You can download the GLPK source distribution from
 * <a href="ftp://ftp.gnu.org/gnu/glpk">ftp://ftp.gnu.org/gnu/glpk</a>.
 */
public class glp_java_vertex_data {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected glp_java_vertex_data(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(glp_java_vertex_data obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GLPKJNI.delete_glp_java_vertex_data(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCut(int value) {
    GLPKJNI.glp_java_vertex_data_cut_set(swigCPtr, this, value);
  }

  public int getCut() {
    return GLPKJNI.glp_java_vertex_data_cut_get(swigCPtr, this);
  }

  public void setPi(double value) {
    GLPKJNI.glp_java_vertex_data_pi_set(swigCPtr, this, value);
  }

  public double getPi() {
    return GLPKJNI.glp_java_vertex_data_pi_get(swigCPtr, this);
  }

  public void setRhs(double value) {
    GLPKJNI.glp_java_vertex_data_rhs_set(swigCPtr, this, value);
  }

  public double getRhs() {
    return GLPKJNI.glp_java_vertex_data_rhs_get(swigCPtr, this);
  }

  public void setSet(int value) {
    GLPKJNI.glp_java_vertex_data_set_set(swigCPtr, this, value);
  }

  public int getSet() {
    return GLPKJNI.glp_java_vertex_data_set_get(swigCPtr, this);
  }

  public glp_java_vertex_data() {
    this(GLPKJNI.new_glp_java_vertex_data(), true);
  }

}
