/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gnu.glpk;


/**
 * Wrapper class for pointer generated by SWIG.
 * <p>Please, refer to doc/glpk-java.pdf of the GLPK for Java distribution
 * and to doc/glpk.pdf of the GLPK source distribution
 * for details. You can download the GLPK source distribution from
 * <a href="ftp://ftp.gnu.org/gnu/glpk">ftp://ftp.gnu.org/gnu/glpk</a>.
 */
public class glp_java_arc_data {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected glp_java_arc_data(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(glp_java_arc_data obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GLPKJNI.delete_glp_java_arc_data(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCap(double value) {
    GLPKJNI.glp_java_arc_data_cap_set(swigCPtr, this, value);
  }

  public double getCap() {
    return GLPKJNI.glp_java_arc_data_cap_get(swigCPtr, this);
  }

  public void setCost(double value) {
    GLPKJNI.glp_java_arc_data_cost_set(swigCPtr, this, value);
  }

  public double getCost() {
    return GLPKJNI.glp_java_arc_data_cost_get(swigCPtr, this);
  }

  public void setLow(double value) {
    GLPKJNI.glp_java_arc_data_low_set(swigCPtr, this, value);
  }

  public double getLow() {
    return GLPKJNI.glp_java_arc_data_low_get(swigCPtr, this);
  }

  public void setRc(double value) {
    GLPKJNI.glp_java_arc_data_rc_set(swigCPtr, this, value);
  }

  public double getRc() {
    return GLPKJNI.glp_java_arc_data_rc_get(swigCPtr, this);
  }

  public void setX(double value) {
    GLPKJNI.glp_java_arc_data_x_set(swigCPtr, this, value);
  }

  public double getX() {
    return GLPKJNI.glp_java_arc_data_x_get(swigCPtr, this);
  }

  public glp_java_arc_data() {
    this(GLPKJNI.new_glp_java_arc_data(), true);
  }

}
