/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.gnu.glpk;


/**
 * Wrapper class for pointer generated by SWIG.
 * <p>Please, refer to doc/glpk-java.pdf of the GLPK for Java distribution
 * and to doc/glpk.pdf of the GLPK source distribution
 * for details. You can download the GLPK source distribution from
 * <a href="ftp://ftp.gnu.org/gnu/glpk">ftp://ftp.gnu.org/gnu/glpk</a>.
 */
public class glp_prob {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected glp_prob(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(glp_prob obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GLPKJNI.delete_glp_prob(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHidden_internal(int value) {
    GLPKJNI.glp_prob_hidden_internal_set(swigCPtr, this, value);
  }

  public int getHidden_internal() {
    return GLPKJNI.glp_prob_hidden_internal_get(swigCPtr, this);
  }

  public glp_prob() {
    this(GLPKJNI.new_glp_prob(), true);
  }

}
